### ISSUE TITLE
Replace ECDSA with Schnorr signature

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#258]
It's ready now.

**Comment by kseo** [comment]
Some preparation patches were landed: 6359ab083610744c35a0b53b10345513f9afb91e, 9a78f4561801b7bda73c215f49cc7e25daa58eac, c4f49a8366f7e3c2c039dc24df1e8840b2cd8a7c, 37a34b8f075a0f48f293de2b3b9929eb5e81ba84, 418d4721d874eaa6bf4dbb8981e9f5a74058f97d, 94ef1e634610947734100ffc79eef5db5a064baa, 0990b704e4d790816e6b9195c4271eb905ebbabd, 6e78e958dac62a16cf402d2e704086663ebdadf6

**Comment by jhs7jhs** [comment]
### To-do
- [ ] Read the issues in `libsecp256k1` which are related to Schnorr signature.
- [ ] Make a demo for Schnorr signature.
- [ ] Implement Schnorr signature in the CodeChain primitives and the SDK.

**Comment by jhs7jhs** [comment]
We are going to use the Schnorr signature scheme which is proposed for Bitcoin, because of the library we're using.

**Comment by jhs7jhs** [comment]
Currently working on the primitives, can check out from https://github.com/CodeChain-io/codechain-primitives-js/issues/25.
Also, I've written the demo code but going to fix it to use Schnorr functions of the primitives.

**Comment by jhs7jhs** [comment]
Finished working on the primitives.

**Comment by jhs7jhs** [comment]
Finished working on CodeChain and the SDK.
CodeChain: https://github.com/CodeChain-io/codechain/commits/schnorr
codechain-sdk-js: https://github.com/codechain-io/codechain-sdk-js/tree/schnorr
codechain-keystore-js: https://github.com/CodeChain-io/codechain-keystore-js/tree/schnorr

**Comment by jhs7jhs** [comment]
Might need to change the code of `libsecp256k1`. See https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki#cite_note-4, the current code uses the option 2.

**Comment by sgkim126** [comment]
@jhs7jhs What is the current status of this issue? Is there something to do?

**Comment by jhs7jhs** [comment]
@sgkim126 Currently the basic implementation is finished, but it's based on experimental part of the old version of the bitcoin library, so it is quite dangerous to merge.
Also, MuSig signing is not supported yet, and needed to be implemented.
