### ISSUE TITLE
Fix skipping integration test cases

### ISSUE THREAD

**Issue by jhs7jhs** [CodeChain-io/codechain#761]
## Test cases not implemented
- [ ] `chain_executeTransactions`, `chain_getNumberOfShards`, `chain_getShardRoot`, `chain_getMiningReward` in `chain.test.ts`
- [ ] Sending invalid parcels over the limits on actions `SetShardOwners`, `SetShardUsers`, `UnwrapCCC` in `verification.test.ts`
- [ ] `mint amount U64 max`, `mint amount exceeds U64` in `transactions.test.ts`
- [ ] Sending invalid parcels over the limits on actions `AssetTransactionGroup`, `WrapCCC` in `verification.test.ts`

## Issues affecting implemented test cases
- [x] Fix the integration test that tests block sync between 2 nodes (#662)
  - Affecting `sync`, need to check again after fixing #759 
- [ ] Listener node fails to accept while initiator node succeeds to connect (#744)
  - Affecting `discovery`
- [ ] Connection is refused right after accepted with InvalidStream error (#745)
  - Affecting `discovery`
- [x] Timer is unstable on Travis (#759)
  - Affecting `discovery`, `mempool`, `network`, `reward`, `sync`
- [x] Connection establishment is slow on Travis (#760)
  - Affecting `discovery`, `mempool`, `network`, `reward`, `sync`

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1326 fixed the last test that Travis skipped.
