### ISSUE TITLE
Support dynamic validator set changes

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#86]
Validators can join/leave the network.

**Comment by sgkim126** [comment]
I think this can be done in three steps.

* [ ] . Split validators and stakeholders.
    - A stakeholder can delegate their stake to a validator.
    - Delegation to none-validator is an invalid transaction.
* [ ] Make a validator become a proposer in proportion to the delegated stake.
* [ ] Make a stakeholder be able to delegate their stake to anybody.

**Comment by sgkim126** [comment]
@foriequal0 Please make the delegation to the invalid validators a syntax error.

**Comment by sgkim126** [comment]
@foriequal0 Don't forget that we should support both of the current static validators and new dynamic validators.
I think you should add a new field to CommonParams to distinguish the validator configuration.

**Comment by foriequal0** [comment]
### WIP
- [ ] Term change
### TODO
- [ ] Nomination
  - [ ] Self-nomination
  - [ ] Nomination
  - [ ] Expiration
- [ ] Election
  - [ ] Election
  - [ ] Validator selection
  - [ ] End of term
- [ ] Punish
	- [ ] Ban
	- [ ] Jail

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1574 closes it.
